name: Build Website to APK (arm64-v8a)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk android-sdk zip

      - name: Generate Signing Key
        run: ./make.sh keygen

      - name: Build APK (arm64-v8a only)
        run: ./make.sh build arm64-v8a

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AnimeKai-APK-arm64-v8a
          path: ./out/*-arm64-v8a.apk
